name: Playwright Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  e2e-tests:
    name: 'Playwright E2E Tests'
    timeout-minutes: 5                                    # Current test runtime is around 1 minute
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-noble   # Use Playwright Docker image
      options: --ipc=host                                 # Enables shared memory (shm) access to prevent browser crashes and improve performance
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    # - name: Configure Sensitive Variables
    #   run: curl -sfS https://dotenvx.sh/install.sh | sh
      env:
        DOTENV_PRIVATE_KEY_CI: ${{ secrets.DOTENV_PRIVATE_KEY_CI }}
    - name: Install dependencies
      run: npm ci
    - name: Environment variables setup                   # Read environment variables and ensure that they can be decrypted
      run: dotenvx run -- node build.js
      env:
        DOTENV_PRIVATE_KEY_CI: ${{ secrets.DOTENV_PRIVATE_KEY_CI }}
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        HOME: /root                                       # Set the HOME environment variable to a writable directory, ie so Firefox browser can run
      run: xvfb-run npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
